theme: jekyll-theme-minimal
title: Taoyang Jia
description: MSCS @ Stanford, Stanford Movement Lab
logo: img/taoyang.png

author:
  name: Taoyang Jia
  avatar: img/taoyang.png
  bio: "MSCS @ Stanford<br>Stanford Movement Lab<br>Prev. UW CSE RAIVN Lab"
  email: toberjia@stanford.edu
  googlescholar: https://scholar.google.com/citations?user=jll93-IAAAAJ&hl=en
  github: ToberJ
  linkedin: https://www.linkedin.com/in/taoyang-jia-84842323a/
